### ISSUE TITLE
后台数据如何获取

### ISSUE THREAD

**Issue by suwu150** [SYSUMonkeyEye/MonkeyEye-FE#27]
后台数据如何获取，我看见使用了axios，但是没有看到数据库文件，是通过远程数据库吗？还是有其他操作

**Comment by hongchh** [comment]
项目使用了http-proxy-middleware将前端发出的请求转发到真正的后台。服务端的详情请查看https://github.com/SYSUMonkeyEye/MonkeyEye-Server
